"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['ZombieInvasion.py']

DATA_FILES = ['HomeScreen.png','icon.png','Bullet.png','12.png','13.png',
'1.png','2.png','3.png','4.png','5.png','6.png','7.png','8.png',
'go_1.png','go_2.png','go_3.png','go_4.png','go_5.png','go_6.png','go_7.png','go_8.png','go_9.png','go_10.png',
'go_1L.png','go_2L.png','go_3L.png','go_4L.png','go_5L.png','go_6L.png','go_7L.png','go_8L.png','go_9L.png','go_10L.png',
'SkyNight.png','GamePlatform.png','Heart.png',
'Starjedi.ttf','Chernobyl.ttf',
'MainMenu.wav','Fireball.wav','background.wav','Jump.wav','Zombie.wav','Hit.wav','MainGame.py',
'top_scores.pickle','Oswald.ttf']

OPTIONS = {
    'iconfile':'iconfile/app.icns'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
